---
- debug:
    msg: "Host is {{ ansible_hostname }}"
- name: Copy application WAR file to host
  copy: 
    src: "{{ war_file }}"
    dest: /tmp

- name: Backup oringinal war file
  file:
    path: /root/backup
    state: directory 
- stat:
    path: "{{ jboss_app_deployment_path }}/{{ app_name }}.war"
  register: stat_result
- debug:
    var: stat_result
- copy:
    src: "{{ jboss_app_deployment_path }}/{{ app_name }}.war"
    dest: "/root/backup/{{ app_name }}-{{ ansible_date_time.epoch }}.war"
    remote_src: true
  when: stat_result.stat.exists

- name: Deployment of new application
  jboss:
    deployment: "{{ app_name }}.war"
    deploy_path: "{{ jboss_app_deployment_path }}"
    src: "/tmp/{{ war_file }}"
    state: present
  when: upgrade == 'False'

- name: Upgrade Application
  jboss:
    deployment: "{{ app_name }}.war"
    deploy_path: "{{ jboss_app_deployment_path }}"
    src: "/tmp/{{ war_file }}"
    state: present
  when: upgrade == 'True'

