---
- name: Check webserver for correct response
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_host'] }}:8080/{{ app_name }}/status.html"
    return_content: yes
  retries: 10
  delay: 1
  register: result
  delegate_to: localhost
- name: show result
  debug:
    msg: "{{ inventory_hostname }} service status is OK"
  when: result.status == 200

